modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="xpanded"
version="1.0.0"
displayName="XPanded"
credits="TrollfaceDev, Ruru and Fred."
displayURL="https://www.curseforge.com/minecraft/mc-mods/xpanded"
authors="Trollface Team"

[[dependencies.xpanded]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




